"""
Django settings for book_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%v+$^=u=%8_cym@j=2n3h$5ywjtk=gz9k_(clkre3rn@1s13o)"

# Debug mode ON (only for development)
DEBUG = True

# Allowed hosts (empty for local development)
ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",      # Django authentication (login, logout)
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "book_app",                 # Our custom app
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "book_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Main templates folder
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",     # debug info
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "book_app.context_processors.wishlist_count",   # wishlist count for navbar
            ],
        },
    },
]

WSGI_APPLICATION = "book_project.wsgi.application"


# Database configuration (SQLite)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation (disabled for learning stage)
AUTH_PASSWORD_VALIDATORS = []


# Language & time zone
LANGUAGE_CODE = "en-us"
USE_I18N = True
TIME_ZONE = "Asia/Kolkata"
USE_TZ = True



# ================= STATIC FILES =================
# Used for CSS, JS, icons
STATIC_URL = "/static/"


# ================= MEDIA FILES =================
# Used for uploaded images (book covers)
MEDIA_URL = "/media/"               # URL to access images
MEDIA_ROOT = BASE_DIR / "media"     # Folder where images are stored


# ================= AUTHENTICATION =================
# Redirect rules for login/logout
LOGIN_URL = "login"                 # Redirect if user not logged in
LOGIN_REDIRECT_URL = "home"         # After successful login
LOGOUT_REDIRECT_URL = "home"        # After logout