# Generated by Django 6.0 on 2026-01-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
