# Generated by Django 6.0 on 2026-02-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_images/"
            ),
        ),
    ]
