# Generated by Django 6.0 on 2026-01-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0003_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
