# Generated by Django 6.0 on 2026-02-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0003_category_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                default="category_images/default.png",
                upload_to="category_images/",
            ),
        ),
    ]
