# Generated by Django 6.0 on 2026-02-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0004_rename_name_category_title_category_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("image", models.ImageField(upload_to="related_items/")),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
