# Generated by Django 6.0 on 2026-02-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0005_relateditem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RelatedItem",
        ),
        migrations.AddField(
            model_name="book",
            name="product_type",
            field=models.CharField(
                choices=[("book", "Book"), ("accessory", "Accessory")],
                default="book",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
