# Generated by Django 6.0 on 2026-01-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0006_cart_cartitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="price",
            new_name="total_price",
        ),
        migrations.RemoveField(
            model_name="order",
            name="book",
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book_app.book"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="book_app.order",
                    ),
                ),
            ],
        ),
    ]
