# Generated by Django 6.0 on 2026-02-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0006_delete_relateditem_book_product_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
