# Generated by Django 6.0 on 2026-03-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0007_alter_book_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
