# Generated by Django 6.0 on 2026-04-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0008_alter_userprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
