# Generated by Django 6.0 on 2026-01-14 14:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0008_wishlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "book")},
        ),
    ]
