# Generated by Django 6.0 on 2026-01-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0009_alter_wishlist_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="book",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="book",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(default="exit"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_city",
            field=models.CharField(default="exit", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_phone",
            field=models.CharField(default="Not provided", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_pincode",
            field=models.CharField(default="Not provided", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
