# Generated by Django 6.0 on 2026-01-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0012_remove_order_shipping_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
