# Generated by Django 6.0 on 2026-01-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0013_alter_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="ordered_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
