# Generated by Django 6.0 on 2026-02-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0015_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=255),
        ),
    ]
